name: Keep Awake Every Minute

on:
  workflow_dispatch: # Se ejecuta manualmente

jobs:
  ping-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Loop infinito de ping
        run: |
          while true
          do
            echo "Haciendo ping a la URL..."
            curl -X GET https://riga.onrender.com
            sleep 60
          done
